### ISSUE TITLE
Hide header

### ISSUE THREAD

**Issue by ArnoStrasbourg** [mykle1/MMM-PopulationClock#1]
Hi @mykle1 

Where/how can I hide the title and the text please ?

**Comment by mykle1** [comment]
Are you referring to the words "World population"? If so, that cannot be altered. Why? Because this module is simply embedded html in an iframe module. There is no option to remove it from the source

**Comment by ArnoStrasbourg** [comment]
ok, thank you

**Comment by ArnoStrasbourg** [comment]
Hi @mykle1 
Our or my chance is that the header is under the counter. So I reduced the height of the frame.
Here is the result : 

![20200526_181629](https://user-images.githubusercontent.com/6398055/82925229-bb47e180-9f7d-11ea-9fe3-69301e06adbd.jpg)

Have a good day.
