### ISSUE TITLE
Wrong population numbers

### ISSUE THREAD

**Issue by EineGrosseBanane69** [mykle1/MMM-PopulationClock#2]
Hi, 
I downloaded this MagicMirrorModule and it works. It shows me the amount of people living. The problem is that the number is different from the site it is getting the data from. The difference is 40 million people.

**Comment by mykle1** [comment]
It's not getting the data from the website. It's getting the data from the api. The only way I could match the website would be to scrape the data and rewrite the module. That's not gonna happen. I'm glad you are interested in the module but this is not something I can correct. 

Feel free to fork the module and make your own modifications 

Peace
